/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package montrash_oneforall.view;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import montrash_oneforall.controler.Function;

/**
 *
 * @author Sheillya
 */
public class formRegister extends javax.swing.JFrame {

    /**
     * Creates new form formRegister
     */
    public formRegister() {
        initComponents();
        this.setLocationRelativeTo(null);
        taAlamatRegis.setLineWrap(true);
    }
    Function f = new Function();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btRegis = new javax.swing.JButton();
        pfPasswordRegis = new javax.swing.JPasswordField();
        pfKonfPasswordRegis = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNamaRegis = new javax.swing.JTextField();
        tfEmailRegis = new javax.swing.JTextField();
        tfNoHpRegis = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAlamatRegis = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrasi");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setMinimumSize(null);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(250, 250, 250));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btRegis.setBackground(new java.awt.Color(173, 244, 91));
        btRegis.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btRegis.setForeground(new java.awt.Color(255, 255, 255));
        btRegis.setText("TAMBAHKAN");
        btRegis.setBorder(null);
        btRegis.setBorderPainted(false);
        btRegis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRegis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btRegisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btRegisMouseExited(evt);
            }
        });
        btRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisActionPerformed(evt);
            }
        });

        pfPasswordRegis.setToolTipText("");
        pfPasswordRegis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 244, 91), 2));

        pfKonfPasswordRegis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 244, 91), 2));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Password");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Konfirmasi Password");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pfPasswordRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 62, Short.MAX_VALUE))
                    .addComponent(pfKonfPasswordRegis)))
            .addComponent(btRegis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pfKonfPasswordRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfPasswordRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nama Lengkap");

        tfNamaRegis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 244, 91), 2));
        tfNamaRegis.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tfEmailRegis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 244, 91), 2));
        tfEmailRegis.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tfNoHpRegis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 244, 91), 2));
        tfNoHpRegis.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfNoHpRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoHpRegisActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("NO Telp");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(164, 94));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(164, 94));
        jScrollPane1.setWheelScrollingEnabled(false);

        taAlamatRegis.setColumns(20);
        taAlamatRegis.setRows(5);
        taAlamatRegis.setAutoscrolls(false);
        taAlamatRegis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 244, 91), 2));
        taAlamatRegis.setMaximumSize(new java.awt.Dimension(162, 92));
        taAlamatRegis.setMinimumSize(new java.awt.Dimension(162, 92));
        jScrollPane1.setViewportView(taAlamatRegis);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Alamat");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tfNamaRegis)
            .addComponent(tfEmailRegis)
            .addComponent(tfNoHpRegis)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNamaRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(tfEmailRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNoHpRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setColor(JButton in){
        in.setBackground(new Color(66,184,131));
    }
    public void resetColor(JButton in1){
        in1.setBackground(new Color(173, 244, 91));
    }
    private void tfNoHpRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoHpRegisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoHpRegisActionPerformed

    private void btRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisActionPerformed
        // TODO add your handling code here:
        if(tfNamaRegis.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong.", "ALERT", JOptionPane.WARNING_MESSAGE);
        }else if(taAlamatRegis.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Alamat tidak boleh kosong.", "ALERT", JOptionPane.WARNING_MESSAGE);
        }else if(tfEmailRegis.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Email tidak boleh kosong.", "ALERT", JOptionPane.WARNING_MESSAGE);
        }else if(tfNoHpRegis.getText().equals("")){
            JOptionPane.showMessageDialog(this, "No HP tidak boleh kosong.", "ALERT", JOptionPane.WARNING_MESSAGE);
        }else if(pfPasswordRegis.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Password tidak boleh kosong.", "ALERT", JOptionPane.WARNING_MESSAGE);
        }else if(pfKonfPasswordRegis.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Anda belum mengkonfirmasi password.", "ALERT", JOptionPane.WARNING_MESSAGE);
        }else{
            //Jika password dan KonfPassword tidak sama, maka dimunculkan pesan error
            if(!pfPasswordRegis.getText().equals(pfPasswordRegis.getText())){
                JOptionPane.showMessageDialog(this, "Password tidak sama.", "ALERT", JOptionPane.WARNING_MESSAGE);
            }else{
                String nama=tfNamaRegis.getText();
                String alamat=taAlamatRegis.getText();
                String email=tfEmailRegis.getText();
                String noHp=tfNoHpRegis.getText();
                String password=f.sha1(pfKonfPasswordRegis.getText());
                if(f.register(nama, alamat, email, noHp, password)==true){
                   this.dispose();
                }
            }
        }
    }//GEN-LAST:event_btRegisActionPerformed

    private void btRegisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegisMouseExited
        // TODO add your handling code here:
        resetColor(btRegis);
    }//GEN-LAST:event_btRegisMouseExited

    private void btRegisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegisMouseEntered
        // TODO add your handling code here:
        setColor(btRegis);
    }//GEN-LAST:event_btRegisMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegis;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField pfKonfPasswordRegis;
    private javax.swing.JPasswordField pfPasswordRegis;
    private javax.swing.JTextArea taAlamatRegis;
    private javax.swing.JTextField tfEmailRegis;
    private javax.swing.JTextField tfNamaRegis;
    private javax.swing.JTextField tfNoHpRegis;
    // End of variables declaration//GEN-END:variables
}
